### ISSUE TITLE
Fails if cert is self signed and need to update to LetsEncrypt Cert

### ISSUE THREAD

**Issue by ghost** [TheBlackPacket/ArubaCertificateUpdater#1]
The check if the certificate is valid or not, does not check if its a self signed cert. Self signed certs typically are a year long so a new install on ClearPass requires a manual run first without the flag -t.

**Comment by TheBlackPacket** [comment]
Found this documentation and will be implementing soon
https://stackoverflow.com/questions/56763385/determine-if-ssl-certificate-is-self-signed-using-python
